name: Deploy pages
on: [push]
jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build pages
        run: |
          cd ${{ github.workspace }} && ./run_in_docker.sh ./build.sh
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
